[project]
name = "vllm-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "huggingface-hub[cli]>=0.33.4",
    "openai>=1.95.1",
]
